runtime: python39
entrypoint: python app.py

env_variables:
  SECRET_KEY: "your_very_secret_key"  # Replace with a secure key
  DB_NAME: "nh_candidates"
  DB_USER: "postgres"
  GCS_BUCKET: "nh-candidate-uploads"  # Replace with your actual bucket name

beta_settings:
  cloud_sql_instances: "ctehr-453623:us-central1:nh-candidate-tracker"

handlers:
  - url: /robots.txt
    static_files: robots.txt
    upload: robots.txt
  - url: /.*
    script: auto